// Code generated by ts2go. DO NOT EDIT.

package grammars

import "github.com/drummonds/gotreesitter"

// AbnfLanguage returns the abnf language definition.
func AbnfLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("abnf.bin")
}
