// Code generated by ts2go. DO NOT EDIT.

package grammars

import "codeberg.org/hum3/gotreesitter"

// AbnfLanguage returns the abnf language definition.
func AbnfLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("abnf.bin")
}
