// Code generated by ts2go batch. DO NOT EDIT.

package grammars

func init() {
	Register(LangEntry{
		Name:           "asm",
		Extensions:     nil,
		Language:       AsmLanguage,
		HighlightQuery: asmHighlightQuery,
		TokenSourceFactory: defaultTokenSourceFactory("asm"),
	})
}

const asmHighlightQuery = ""
