// Code generated by ts2go. DO NOT EDIT.

package grammars

import "codeberg.org/hum3/gotreesitter"

// GolucaLanguage returns the goluca language definition.
func GolucaLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("goluca.bin")
}
