// Code generated by cmd/gen_linguist; DO NOT EDIT.
// Re-generate: go run ./cmd/gen_linguist -manifest grammars/languages.manifest

package grammars

// linguistToGrammar maps lowercased linguist names and aliases to
// gotreesitter grammar names.
var linguistToGrammar = map[string]string{}

// grammarDisplayNames maps gotreesitter grammar names to their
// linguist canonical display name.
var grammarDisplayNames = map[string]string{}
