// Code generated by ts2go. DO NOT EDIT.

package grammars

import "github.com/drummonds/gotreesitter"

// PtaLanguage returns the pta language definition.
func PtaLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("pta.bin")
}
