// Code generated by ts2go. DO NOT EDIT.

package grammars

import "github.com/drummonds/gotreesitter"

// YabnfLanguage returns the yabnf language definition.
func YabnfLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("yabnf.bin")
}
